#!/usr/bin/env bash
# disclaimer — Legal Disclaimer Reference
# Powered by BytesAgain | bytesagain.com | hello@bytesagain.com
set -euo pipefail

VERSION="1.0.0"

cmd_intro() {
    cat << 'EOF'
=== Disclaimers Overview ===

A disclaimer is a statement intended to limit liability, specify
the scope of rights and obligations, or clarify the nature of content
being provided.

Purpose of Disclaimers:
  1. Limit legal liability for the provider
  2. Set user expectations about content quality
  3. Comply with regulatory disclosure requirements
  4. Clarify intellectual property rights
  5. Disclose material relationships (affiliates, sponsors)
  6. Protect against misinterpretation of advice

Legal Basis:
  Contract Law     Disclaimers as terms of use (click-wrap/browse-wrap)
  UCC Article 2    Warranty disclaimers in product sales
  Tort Law         Limiting negligence liability
  Consumer Law     FTC disclosure requirements
  Securities Law   SEC-mandated investment disclaimers
  Professional Law License-specific disclaimer requirements

Enforceability Factors:
  ✓ Conspicuous placement (not buried in fine print)
  ✓ Clear, plain language (not overly legalistic)
  ✓ User had opportunity to read before engaging
  ✓ Reasonable scope (not disclaiming everything)
  ✓ Consistent with actual practices
  ✗ Cannot disclaim gross negligence or fraud
  ✗ Cannot override statutory consumer rights
  ✗ Cannot disclaim liability for personal injury (most jurisdictions)
  ✗ Unconscionable terms may be struck down

Key Legal Terms:
  "As Is"              No warranties of any kind
  "For informational   Not professional advice
   purposes only"
  "Use at your         User assumes all risk
   own risk"
  "No warranty"        Excludes implied warranties
  "Limitation of       Caps financial exposure
   liability"
  "Hold harmless"      User agrees not to sue
EOF
}

cmd_types() {
    cat << 'EOF'
=== Disclaimer Types ===

1. General Disclaimer
   Broad limitation of liability for website/service
   "This website is provided 'as is' without warranties."

2. Professional Advice Disclaimer
   Clarifies content is not professional advice
   "Nothing on this site constitutes medical/legal/financial advice."

3. Warranty Disclaimer
   Excludes implied warranties (merchantability, fitness)
   Required by UCC to be conspicuous (CAPS or bold)

4. Liability Limitation
   Caps maximum damages recoverable
   "Our total liability shall not exceed fees paid in last 12 months."

5. Affiliate/Sponsorship Disclaimer
   FTC-required disclosure of material relationships
   "This post contains affiliate links. I may earn a commission."

6. Copyright/IP Disclaimer
   Clarifies ownership and permitted use
   "All trademarks are property of their respective owners."

7. Fair Use Disclaimer
   For educational/commentary use of copyrighted material
   "This content is used for commentary under fair use."

8. Views & Opinions Disclaimer
   Personal views vs organizational positions
   "Views expressed are the author's own, not the employer's."

9. Investment Disclaimer
   SEC-required for financial content
   "Past performance does not guarantee future results."

10. Medical Disclaimer
    For health-related content
    "This is not medical advice. Consult your healthcare provider."

11. Testimonial Disclaimer
    FTC-required for endorsements
    "Results may vary. Testimonials are not guarantees."

12. AI/Generated Content Disclaimer
    For AI-produced content
    "This content was generated by AI and may contain errors."

13. External Links Disclaimer
    Limiting liability for linked content
    "We are not responsible for content on external websites."

14. Errors & Omissions (E&O)
    For content accuracy
    "While we strive for accuracy, we make no guarantees."

15. Confidentiality Disclaimer
    For emails and communications
    "This message is confidential. If received in error, delete."
EOF
}

cmd_website() {
    cat << 'EOF'
=== Website Disclaimers ===

Essential Website Disclaimers:

  1. Terms of Use / Terms of Service
     - Governs use of the website
     - Includes acceptable use policy
     - Specifies governing law and jurisdiction
     - Contains dispute resolution mechanism

  2. Privacy Policy (legally required in most jurisdictions)
     - What data is collected
     - How data is used and shared
     - User rights (access, deletion)
     - Cookie policy
     - Required by: GDPR, CCPA, CalOPPA, COPPA

  3. General Disclaimer
     - Content accuracy limitations
     - "As is" provision
     - No guarantee of availability
     - Right to modify content

  4. Cookie Notice
     - Types of cookies used
     - Purpose of each cookie
     - How to manage/disable cookies
     - Required by: GDPR, ePrivacy Directive

Placement Best Practices:
  Footer link     Persistent access from every page
  Banner/popup    For cookie consent (before cookies set)
  Registration    Terms checkbox during signup
  Checkout        Terms link near payment button
  Blog posts      Disclaimer at top or bottom of articles
  Landing pages   Near forms that collect data

Click-Wrap vs Browse-Wrap:
  Click-wrap (stronger):
    User must affirmatively agree (check box, click "I agree")
    Generally enforceable in courts
    Use for: signups, purchases, downloads

  Browse-wrap (weaker):
    Terms posted via hyperlink, no active consent required
    Enforceability varies — depends on conspicuousness
    Use for: informational websites, blogs

Browsewrap Enforcement Tips:
  - Place link in prominent location (not just footer)
  - Use contrasting color for the link
  - Reference terms at key interaction points
  - Log user access patterns (prove they were exposed)
EOF
}

cmd_professional() {
    cat << 'EOF'
=== Professional Disclaimers ===

Medical Disclaimer:
  Essential elements:
  - Content is for informational purposes only
  - Does NOT constitute medical advice
  - Not a substitute for professional medical consultation
  - Always consult a qualified healthcare provider
  - Do not disregard professional advice based on this content
  - Call emergency services for medical emergencies

  Required when:
  - Health/wellness blog or website
  - Supplement or nutrition content
  - Mental health resources
  - Exercise or fitness programs
  - First aid or symptom information

Financial/Investment Disclaimer:
  Essential elements:
  - Not financial advice or investment recommendation
  - Past performance does not indicate future results
  - Investments involve risk of loss
  - Author may hold positions in mentioned securities
  - Consult a qualified financial advisor
  - Consider your personal financial situation

  SEC requirements:
  - Registered investment advisors must disclose conflicts
  - Performance claims must include specific disclosures
  - Testimonials require specific disclaimers

Legal Disclaimer:
  Essential elements:
  - Does not create attorney-client relationship
  - Not a substitute for legal advice from licensed attorney
  - Laws vary by jurisdiction
  - Consult qualified attorney for your specific situation
  - Information may not reflect current law
  - No guarantee of outcomes

Educational Disclaimer:
  Essential elements:
  - Content is for educational purposes
  - Does not guarantee specific outcomes
  - Not a substitute for formal education/certification
  - Reader responsible for verifying information
  - Applying content is at reader's own risk
  - No professional certification implied

Tax Disclaimer:
  Essential elements:
  - Not tax advice
  - Tax laws change frequently
  - Consult qualified tax professional
  - Individual circumstances vary
  - Author is not a CPA/tax attorney (if true)
EOF
}

cmd_product() {
    cat << 'EOF'
=== Product Disclaimers & Warranties ===

Warranty Types (UCC Article 2):

  Express Warranty:
    Created by seller's statements, descriptions, or samples
    Cannot be disclaimed once made
    Example: "This product will last 5 years"

  Implied Warranty of Merchantability:
    Product is fit for ordinary purpose
    Automatically applies unless disclaimed
    Must be conspicuous to disclaim (CAPS or bold)

  Implied Warranty of Fitness for Particular Purpose:
    When seller knows buyer's specific intended use
    Can be disclaimed with general language

Disclaiming Implied Warranties:
  UCC requires the disclaimer to be CONSPICUOUS:

  "THE PRODUCT IS PROVIDED 'AS IS' WITHOUT WARRANTY OF ANY
  KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
  PARTICULAR PURPOSE."

  Must be:
  - In writing (for merchantability disclaimer)
  - Conspicuous (caps, bold, different color, larger font)
  - Specifically mention "merchantability" to disclaim it

Limitation of Remedies:
  "IN NO EVENT SHALL [COMPANY] BE LIABLE FOR ANY INDIRECT,
  INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES."

  "OUR TOTAL LIABILITY SHALL NOT EXCEED THE PURCHASE PRICE
  OF THE PRODUCT."

Product Liability Disclaimers:
  - Cannot fully disclaim personal injury liability
  - Warning labels are crucial (duty to warn)
  - Age restrictions if applicable
  - Proper use instructions
  - Known hazards and contraindications

Software-Specific (common in open source):
  - "AS IS" without warranty of any kind
  - No liability for data loss
  - No guarantee of bug-free operation
  - No guaranteed support or updates
  - Use at your own risk

Digital Product Disclaimers:
  - No guarantee of compatibility with all devices
  - Results may vary based on implementation
  - No refund after download (where permitted)
  - Intellectual property remains with creator
  - License terms govern use
EOF
}

cmd_regulatory() {
    cat << 'EOF'
=== Regulatory Disclaimers ===

FTC (Federal Trade Commission):

  Endorsement Disclaimers:
  - Material connections must be disclosed
  - "Paid partnership" or "Sponsored"
  - "#ad" or "#sponsored" on social media
  - Must be clear and conspicuous
  - Near the endorsement (not buried elsewhere)

  Affiliate Disclaimers:
  - "This post contains affiliate links"
  - Disclose before the first affiliate link
  - Must be noticeable (not hidden)
  - Apply to: blogs, reviews, social posts, videos

  Testimonial Disclaimers:
  - "Results may vary"
  - "Individual results not guaranteed"
  - Cannot use atypical results without noting typical
  - Must reflect genuine experience

SEC (Securities and Exchange Commission):

  Investment Disclaimers:
  - "Securities involve risk, including loss of principal"
  - Forward-looking statements disclaimer
  - Past performance disclaimers
  - Conflicts of interest disclosure
  - Registered advisor disclosure

FDA (Food and Drug Administration):

  Supplement Disclaimers:
  - "These statements have not been evaluated by the FDA"
  - "This product is not intended to diagnose, treat,
     cure, or prevent any disease"
  - Required for all dietary supplement claims
  - Must be near health-related claims

GDPR (EU Data Protection):
  - Data processing disclosures
  - Legal basis for processing
  - Data subject rights
  - International transfer mechanisms
  - Data retention periods
  - Data protection officer contact

CAN-SPAM:
  - Commercial email identification
  - Opt-out mechanism
  - Physical address of sender
  - Valid subject lines (no deception)

DMCA:
  - Safe harbor notice for user-generated content
  - Designated DMCA agent information
  - Takedown procedure description
  - Counter-notification process
EOF
}

cmd_drafting() {
    cat << 'EOF'
=== Disclaimer Drafting Guidelines ===

Language Principles:

  DO:
  ✓ Use plain language (8th-grade reading level)
  ✓ Be specific about what is disclaimed
  ✓ Use active voice where possible
  ✓ Break into short, readable paragraphs
  ✓ Define key terms
  ✓ Use headings and structure
  ✓ Date the disclaimer (effective date)

  DON'T:
  ✗ Use unnecessary legal jargon
  ✗ Make contradictory statements
  ✗ Disclaim things your marketing promises
  ✗ Copy-paste without understanding
  ✗ Disclaim liability for your own negligence
  ✗ Use overly broad catch-all language
  ✗ Forget to update when business changes

Structure Template:
  1. Scope (what this disclaimer covers)
  2. Content accuracy (limitations)
  3. Professional advice disclaimer (if applicable)
  4. Third-party links/content
  5. Warranty exclusions
  6. Liability limitations
  7. Governing law
  8. Changes to disclaimer
  9. Contact information
  10. Effective date

Common Pitfalls:

  1. Inconsistency with Marketing
     Marketing says: "Guaranteed results!"
     Disclaimer says: "No guarantees of any kind"
     → Disclaimer may be voided by conflicting promises

  2. Burying the Disclaimer
     Hidden in page 47 of terms nobody reads
     → Courts may find it unenforceable

  3. Disclaiming Non-Disclaimable Things
     "Not liable for personal injury" (can't disclaim in most places)
     "Not liable for fraud" (cannot disclaim)
     → Undermines credibility of entire disclaimer

  4. One-Size-Fits-All
     Using same disclaimer across different jurisdictions
     → Different laws, different requirements

  5. Set and Forget
     Never updating after business model changes
     → Outdated disclaimers may not protect current activities

Jurisdiction Considerations:
  US       Generally pro-freedom-of-contract, enforces click-wrap
  EU       Consumer protection limits, GDPR, unfair terms directive
  UK       Consumer Rights Act 2015, CMA guidelines
  Australia ACL prohibits unfair contract terms
  Canada    Provincial consumer protection laws vary
EOF
}

cmd_checklist() {
    cat << 'EOF'
=== Disclaimer Audit Checklist ===

Website Coverage:
  [ ] General website disclaimer present
  [ ] Privacy policy (legally required in most jurisdictions)
  [ ] Terms of use / Terms of service
  [ ] Cookie consent notice
  [ ] Copyright notice
  [ ] Accessibility statement (ADA/WCAG)

Content Disclaimers:
  [ ] Professional advice disclaimer (medical/legal/financial)
  [ ] Accuracy disclaimer (content may contain errors)
  [ ] Third-party content disclaimer
  [ ] User-generated content disclaimer
  [ ] External links disclaimer
  [ ] AI-generated content disclaimer (if applicable)

Commercial Disclaimers:
  [ ] Affiliate disclosure (before first link)
  [ ] Sponsorship disclosure (FTC compliant)
  [ ] Testimonial disclaimers
  [ ] Product warranty disclaimer (conspicuous)
  [ ] Pricing disclaimer ("prices subject to change")
  [ ] Availability disclaimer

Regulatory Compliance:
  [ ] FTC endorsement guidelines met
  [ ] SEC disclaimers (if financial content)
  [ ] FDA disclaimers (if supplement/health)
  [ ] GDPR disclosures (if EU audience)
  [ ] CCPA disclosures (if CA audience)
  [ ] CAN-SPAM compliance (email)
  [ ] COPPA (if children's content)

Quality Checks:
  [ ] All disclaimers are current and dated
  [ ] Language is clear and readable
  [ ] No contradictions with marketing materials
  [ ] Disclaimers are conspicuously placed
  [ ] Click-wrap consent for critical terms
  [ ] Disclaimers reviewed by legal counsel
  [ ] Version history maintained
  [ ] Translated for non-English audiences (if applicable)

Placement Verification:
  [ ] Footer links visible on all pages
  [ ] Cookie banner appears before cookies set
  [ ] Signup flow includes terms checkbox
  [ ] Checkout includes terms reference
  [ ] Blog posts include relevant disclaimers
  [ ] Social media bios include disclosures
  [ ] Email footer includes required notices
EOF
}

show_help() {
    cat << EOF
disclaimer v$VERSION — Legal Disclaimer Reference

Usage: script.sh <command>

Commands:
  intro        Disclaimer overview — purpose, enforceability, legal basis
  types        Disclaimer types — warranty, liability, professional, etc.
  website      Website disclaimer essentials and placement
  professional Medical, financial, legal, and educational disclaimers
  product      Product disclaimers and warranty exclusions
  regulatory   FTC, SEC, FDA, GDPR regulatory disclaimers
  drafting     Drafting guidelines — language, structure, pitfalls
  checklist    Disclaimer audit checklist
  help         Show this help
  version      Show version

Powered by BytesAgain | bytesagain.com
EOF
}

CMD="${1:-help}"

case "$CMD" in
    intro)       cmd_intro ;;
    types)       cmd_types ;;
    website)     cmd_website ;;
    professional) cmd_professional ;;
    product)     cmd_product ;;
    regulatory)  cmd_regulatory ;;
    drafting)    cmd_drafting ;;
    checklist)   cmd_checklist ;;
    help|--help|-h) show_help ;;
    version|--version|-v) echo "disclaimer v$VERSION — Powered by BytesAgain" ;;
    *) echo "Unknown: $CMD"; echo "Run: script.sh help"; exit 1 ;;
esac
